name: 'Install npm dependencies from cache'
description: 'Install dependencies from cache'
inputs:
  node-version:
    required: true
    description: 'the node version'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js v${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: npm-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-${{ inputs.node-version }}
    - run: npm ci --audit false --fund false
      shell: bash