name: Checks

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CI: true

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - uses: ./.github/actions/node
        with:
          node-version: '>=18.18.0'
      - name: Rust linting
        run: |
          make lint-rust
      - name: Typescript linting
        run: |
          make lint-typescript

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [ linting ]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - uses: ./.github/actions/node
        with:
          node-version: '>=18.18.0'
      - name: Unit
        id: unit
        run: |
          make test-unit
      - name: Integration
        id: integration
        if: steps.unit.outcome == 'success'
        run: |
          make build
          make test-integration