name: Preview

on:
  workflow_dispatch:

env:
  CI: true
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
      - uses: ./.github/actions/node
        with:
          node-version: '>=18.18.0'
      - name: Wrangler deploy preview
        run: |
          make deploy-preview
